version: 2
jobs:
  build:
    docker:
      - image: docker:stable
        environment:
          DOCKER_DRIVER: overlay2
          MAJOR_VERSION: '9'
          MINOR_VERSION: '9.0'
          FULL_VERSION: '9.0.0'
          CI_REGISTRY_IMAGE: 'containerinfra/sentry'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true 

      - run: |
          if [ $CIRCLE_BRANCH ]; then 
            docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD 
          fi
          
          docker build --build-arg SENTRY_VERSION=$FULL_VERSION -t $CI_REGISTRY_IMAGE:$FULL_VERSION --label org.opencontainers.image.revision=$CIRCLE_SHA1 .
          
          if [ $CIRCLE_BRANCH ]; then 
            docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:$MINOR_VERSION
            docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:$MAJOR_VERSION
            docker tag $CI_REGISTRY_IMAGE:$FULL_VERSION $CI_REGISTRY_IMAGE:latest
            docker push $CI_REGISTRY_IMAGE:$FULL_VERSION
            docker push $CI_REGISTRY_IMAGE:$MINOR_VERSION
            docker push $CI_REGISTRY_IMAGE:$MAJOR_VERSION
            docker push $CI_REGISTRY_IMAGE:latest
          fi
